# FT analytics settings
ua: 35229645-1 # google analytics. Default is 35229645-1
ij: s # set this to "p" for production or "s" for staging
uuid:
microsite: Interactive

# Site settings
title: FT Visual Journalism
email: interactive@ft.com
description: Telling stories with code from the Financial Times newsroom
base-url: # the subpath of your site, e.g. /blog/
url: # "https://ig.ft.com" # the base hostname & protocol for your site
twitter_username: ftdata
github_username: ft-interactive

# FT Origami settings

# Default social media settings
author: FT Interactive News team
# fb-id: 429755910551755 # ???
fb-page: 8860325749
og-title: Headline for Facebook # delete line to default to title tag
og-type: article
og-img: http://www.ft.com/path/to/default/picture/image.png # image for facebook
og-desc: This is the og description for Facebook # delete to default to page description
# twitterCard: summary_large_image
# twitterSite: FT
google-plus: https://plus.google.com/113457471429583444041/

# Images
favicon: "https://ig.ft.com/favicon.ico"
apple-touch-icon: "//im.ft-static.com/m/icons/apple-touch-icon.png"
social-image: http://www.ft.com/path/to/default/picture/socialmediaimage.png # URL of default social media image

# Origami styles
o-stylesheet: "https://h2.ft.com/build/v2/bundles/css?modules=n-normalize@^1,o-footer@^4,o-fonts@^2,o-grid@^4"

# Bertha
berthakey: "1m8GiTLGQTq2U7LgeL6alAD0jxIygQAqldPOcmDgapq4"
berthsheets: "basic,groups"
